### ISSUE TITLE
Always hide right column

### ISSUE THREAD

**Issue by tresoldi** [frictionlessdata/livemark#199]
I would like to always hide the right column (i.e., `div livemark-right`), no matter the view width, but I was unable to find a way (besides manipulating the output, of course).

Is it possible to use `livemark.yaml` to set its visibility as hidden in all cases?

**Comment by benhur07b** [comment]
Not sure if it can be done via `livemark.yml` but we can add custom styles (to the `style.css` for example) to do this. The link to the CSS file can be added in `livemark.yml`.

## Hiding the right column

```css
#livemark-right {
    display: none !important;
}
```

Results in:
![image](https://user-images.githubusercontent.com/22940966/151646995-aa25ccc8-46f7-47af-a431-a82bd3394ac6.png)


## Hiding the right column and extending the main/middle column to the right

```css
#livemark-main {
  margin-right: 0px !important;
}

#livemark-right {
    display: none !important;
}
```

Results in:
![image](https://user-images.githubusercontent.com/22940966/151647205-447cf563-50bc-402e-a890-efcf8fe95ef3.png)

In this case, the `#livemark-display` element (print-increase/decrease readability-scroll to top) will cover the navigation link to the next page in pages with long content.

See bottom right corner:
![image](https://user-images.githubusercontent.com/22940966/151647271-2f31f264-b3af-47a1-b9ae-432e0212c3e7.png)

This can also be remedied by adding custom CSS.

```css
#livemark-display {
  margin-bottom: 60px !important;
}

#livemark-main {
  margin-right: 0px !important;
}

#livemark-right {
    display: none !important;
}
```

Results in:
![image](https://user-images.githubusercontent.com/22940966/151647409-756b1527-ef98-4b8a-b87b-fa11de306d0f.png)

Or we can simply remove this element by adding the following in `livemark.yml`
```yaml
display: false
```

Results in:
![image](https://user-images.githubusercontent.com/22940966/151647430-f9039159-2056-49e8-a133-cb08ab60e9ff.png)


P.S. I'm guessing it should be possible to automate this into a single parameter that can be added to `livemark.yaml`.
