### ISSUE TITLE
Improve error message for incorrectly set path

### ISSUE THREAD

**Issue by aivuk** [frictionlessdata/livemark#207]
I created a very simple livemark project:
```

ls -l
total 8
-rw-rw-r-- 1 aivuk aivuk 16 Jun 13 10:33 index.md
-rw-rw-r-- 1 aivuk aivuk 55 Jun 13 10:33 livemark.yaml
```

```
➜  livemark-tutorial $ cat livemark.yaml  
pages:
  items:
    - name: Test
      path: index.md

```

```
➜  livemark-tutorial $ cat livemark.yaml 
pages:
  items:
    - name: Test
      path: index.md
```

but when I try to run livemark on the folder with `livemark start` if fails with:

`'NoneType' object has no attribute 'get_plugin'`

@roll

**Comment by roll** [comment]
@aivuk 
Nervermind - I read it wrongly

Let me try

**Comment by roll** [comment]
@aivuk 
The path should be abstract (withouh an extension md/html):

```
➜  livemark-tutorial $ cat livemark.yaml 
pages:
  items:
    - name: Test
      path: index
```
