### ISSUE TITLE
Doc: Starting project fails "No documents to build in the project"

### ISSUE THREAD

**Issue by vlcinsky** [frictionlessdata/livemark#208]
The page: https://github.com/frictionlessdata/livemark/blob/main/pages/getting-started/starting-project.md

gives instructions to start a project but it fails with:

```shell
$ livemark start
No documents to build in the project
```

Obvious reason is, that the file `livemark.yaml` is incomplete:
```yaml
brand:
  text: My Project
site:
  favicon: assets/favicon.ico
```
as it does not contain any `pages` section so there is nothing to build.
